### PR TITLE
[FEATURE] Add parameter config for

### PR DESCRIPTION
**Pull request by Neirda24**
Waiting for https://github.com/Sainsburys/guzzle-oauth2-plugin/pull/16 to be merged

### CODE REVIEW

**Comment by gregurco** [comment]
@Neirda24 don't forget to change version of guzzle-oauth2-plugin in composer.json, after PR will be merged there.

**Comment by Neirda24** [comment]
@gregurco : good point. will do. thanks

**Comment by Neirda24** [comment]
@gregurco : done

**Comment by gregurco** [comment]
@Neirda24 very good. Please fix tests and I will merge it. And also get last changes from master.

**Comment by Neirda24** [comment]
@gregurco : Sorry missed it. Done now

**Comment by florianpreusner** [comment]
Nice 👍

**Comment by gregurco** [comment]
@Neirda24 Thanks. It's merged and released. Could you please write an example when you need "resources" parameter?

**Comment by Neirda24** [comment]
@gregurco : Thanks. Our use case is connecting using oauth2 on an azure webserver. the resource parameter is an URL (as an identifier) which must be secured. it goes with the form params alognside client_id, client_secret and grant_type

**Comment by gregurco** [comment]
@Neirda24 got it, thanks

**Comment by florianpreusner** [comment]
Maybe this can be added in README.md?

**Comment by p5vgregurco** [comment]
@florianpreusner yep, I will add it today later. Probably I will do a little bit more changes with params validation and some tests.

**Comment by gregurco** [comment]
@florianpreusner yep, I will add it today later. Probably I will do a little bit more changes with params validation and some tests.

**Pull request merged**
